version: '3.8'

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.13.2
    container_name: filebeat
    user: root
    volumes:
      - /Users/mrityunjoydey/Documents/github/personal/go-grpc/logs:/logs/go-grpc:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    command: ["--strict.perms=false"]
