filebeat.inputs:
# Monitor local Go application logs
- type: log
  enabled: true
  paths:
    - /logs/sample-go-app/*.log
  json.message_key: message
  fields:
    app: sample-go-app
    environment: development
  fields_under_root: true

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["http://host.docker.internal:9200"]
  username: "elastic"
  password: "tbqo4lbe"

setup.kibana:
  host: "http://host.docker.internal:5601"
  username: "elastic"
  password: "tbqo4lbe"

setup.dashboards.enabled: true
setup.ilm.enabled: false

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
