filebeat.inputs:
# Monitor local Go application logs
- type: log
  enabled: true
  paths:
    - /logs/sample-go-app/*.log
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: message
  fields:
    app: sample-go-app
    environment: development
  fields_under_root: true

# Keep container monitoring for other services
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
  processors:
    - add_docker_metadata: ~
    - decode_json_fields:
        fields: ["message"]
        target: ""
        overwrite_keys: true
        process_array: false
        max_depth: 1

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["http://host.docker.internal:9200"]
  username: "elastic"
  password: "tbqo4lbe"

setup.kibana:
  host: "http://host.docker.internal:5601"
  username: "elastic"
  password: "tbqo4lbe"

setup.dashboards.enabled: true
setup.ilm.enabled: false

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
