version: '3.8'
volumes:
  pgdata:

services:
  postgres:
    image: "postgres:17.5"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - 5432:5432
    volumes:
      - ./infra/dev/db-setup:/docker-entrypoint-initdb.d/:z
      - pgdata:/var/lib/postgresql/data